run:
  deadline: 5m
  skip-dirs:
    - ./testdata

linters-settings:
  gocyclo:
    min-complexity: 10
  lll:
    line-length: 100
  misspell:
    locale: US
  funlen:
    lines: 60
    statements: 40

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - lll
        - stylecheck
        - funlen

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - misspell
    - staticcheck
    - prealloc
    - ineffassign
    - unused
    - gocyclo
    - gosimple
    - structcheck
    - varcheck
    - stylecheck
    - lll
    - deadcode
    - unconvert
    - unparam
    - funlen
    - interfacer
    - maligned
    - gocritic
    - scopelint
