name: ci
on:
  push:
    branches:
    - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.13 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.8
        ./bin/golangci-lint run -v ./...
    - name: Use cache dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
    - name: Download dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Test
      run: go test ./...
